web/router.ex
defmodule JobBoard.Router do
  use Phoenix.Router

  scope alias: JobBoard do
    get "/", PageController, :index, as: :pages
    resources "/jobs", JobController

    get "/users/new", UserController, :new, as: :user
  end
end

web/models/jobs.ex
defmodule JobBoard.Jobs do
  use Ecto.Model

  schema "jobs" do
    field :title, :string
    field :job_type, :string
    field :description, :string
    field :job_status, :string
  end
end

web/models/queries.ex
defmodule JobBoard.Queries do
  import Ecto.Query
  alias JobBoard.Jobs
  alias JobBoard.Repo

  def jobs_query do
    query = from job in Jobs,
            order_by: [desc: job.id],
            select: job
    Repo.all(query)
  end

  def job_detail_query(id) do
    int_id = String.to_integer(id)
    query = from job in Jobs,
            where: job.id == ^int_id,
            select: job
    Repo.all(query) |> List.first
  end
end

web/models/repo.ex
defmodule JobBoard.Repo do
  use Ecto.Repo, adapter: Ecto.Adapters.Postgres

  def conf do
    parse_url "ecto://elixir:rixile@localhost/job_board"
  end

  def priv do
    app_dir(:job_board, "priv/repo")
  end
end

web/controllers/job_controller.ex
defmodule JobBoard.JobController do
  use Phoenix.Controller
  alias JobBoard.Router
  alias JobBoard.Jobs
  alias JobBoard.Repo
  alias JobBoard.Queries

  def index(conn, _params) do
    jobs = Queries.jobs_query
    render conn, "index", jobs: jobs
  end

  def new(conn, _params) do
    render conn, "new"
  end

  def create(conn, params) do
    job = %Jobs{title: params["title"], description: params["description"], job_type: params["type"], job_status: params["status"]}
    Repo.insert(job)
    redirect conn, Router.pages_path(:index)
  end

  def show(conn, params) do
    job = Queries.job_detail_query(params["id"])
    render conn, "job", [job: job, action: params["action"]]
  end

  def edit(conn, %{"id" => id}) do
    job = Queries.job_detail_query(id)
    render conn, "edit", jbo: job
  end

  def update(conn, params) do
    IO.inspect params["type"]
    job = Repo.get(Jobs, params["id"])
    job = %{job | title: params["title"], description: params["description"], job_type: params["type"], jbb_status: params["status"]}
    Repo.update(job)
    redirect conn, Router.pages_path(:index)
  end

  def destroy(conn, params) do
    job = Queries.job_detail_query(params["id"])
    Repo.delete(job)
    redirect conn, Router.pages_path(:index)
  end
end

web/controllers/page_controller.ex
defmodule JobBoard.PageController do
  use Phoenix.Controller
  alias JobBoard.Router
  alias JobBoard.Queries

  def index(conn, _params) do
    jobs = Queries.jobs_query
    render conn, "index", jobs: jobs
  end
end

web/controllers/user_controller.ex
defmodule JobBoard.UserController do
  use Phoenix.Controller
  alias JobBoard.Router

  def new(conn, _params) do
    render conn, "new"
  end
end

web/views/job_view.ex
defmodule JobBoard.JobView do
  use JobBoard.Views

end

web/views/layout_view.ex
defmodule JobBoard.LayoutView do
  use JobBoard.Views

end

web/views/page_view.ex
defmodule JobBoard.PageView do
  use JobBoard.Views

end

web/views/user_view.ex
defmodule JobBaord.UserView do
  use JobBoard.Views
end

web/templates/job/edit.html.eex
<h2>Edit Job</h2>
<form class="form-horizontal" action="/job/<%= @job.id %>" method="post">
  <div class="form-group">
    <label for="title" class="col-sm-2 control-label">Job Title</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" value="<%= @job.title %>" name="title" placeholder="Job Title" required="required">
    </div>
  </div>

  <div class="form-group">
    <label for="description" class="col-sm-2 control-label">Job Description</label>
    <div class="col-sm-10">
      <textarea id="description" placeholder="Job description..." class="form-control" name="description" cols="30" rows="10" required="required"><%= @job.description %></textarea>
    </div>
  </div>

  <div class="form-group">
    <label for="type" class="col-sm-2 control-label">Job Type</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="type" id="type" value="<%= @job.job_type %>" placeholder="Job Type">
    </div>
  </div>

  <div class="form-group">
    <label for="status" class="col-sm-2 control-label">Job Status</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="status" value="<%= @job.job_status %>" placeholder="Job Status">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-warning">Update</button>
    </div>
  </div>

</form>

web/templates/job/index.html.eex
<div class="row">
  <div class="col-md-4">
    <h2>List Of Jobs</h2>
  </div>
  <div class="col-md-8">
    <a href="<%= job_path(:new) %>" class="btn btn-danger pull-right">Post a new job</a>
  </div>
</div>

<ul class="list-unstyled" style="">
<%= for job <- @jobs do %>
  <li class="job-list">
    <div class="row">
      <div class="col-md-9">
        <a href="/job/<%= job.id %>">
          <span class="title"><%= job.title %></span>
          <span class="label label-success"><%= job.job_type %></span>
          <span class="label label-default"><%= job.job_status %></span>
        </a>
      </div>
      <div class="col-md-3 buttons" style="text-align: right">
        <form method="post" action="<%= job_path(:destroy, job.id) %>" >
          <a href="<%= job_path(:edit, job.id) %>" class="btn btn-warning btn-sm">Edit</a>&&nbsp; &nbsp;
          <input type="hidden" name="_method" value="DELETE">
          <button type="submit" class="btn btn-default btn-sm">Delete</button>
        </form>
      </div>
    </div>
  </li>
<% end %>
</ul>

web/templates/job/job.html.eex
<div class="row">
  <div class="col-md-12">
    <%= if @action == "delete" do %>
      <h2>Are you sure you want to delete <%= @job.title %>?</h2>
    <% else %>
      <h2><%= @job.title %></h2>
    <% end %>
    <h4>
      <span class="label label-success">
        <%= @job.job_type %>
      </span> &nbsp;
      <span class="label label-default">
        <%= @job.job_status %>
      </span>
    </h4>
  </div>
  <div class="col-md-12">
    <p>
      <%= @job.description %>
    </p>
  </div>
  <div class="col-md-12">
    <form action="<%= job_path(:destro, @job.idy) %>" method="post">
      <a href="/" class="btn btn-success">Back</a>
      <%= if @action == "delete" do %>
        <input type="hidden" name="id" value="<%= @job.id %>">
        <button type="submit" class="btn btn-danger pull-right">Delete</button>
      <% end %>
    </form>
  </div>
</div>

web/templates/job/new.html.eex
<div class="row">
  <div class="col-lg-12">
    <h1>New Job</h1>
    <form class="form-horizontal" action="<%= job_path(:create) %>" method="post">

     <div class="form-group">
        <label for="title" class="col-sm-2 control-label">Job Title</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="title" name="title" placeholder="Job Title" required="required">
        </div>
     </div>

     <div class="form-group">
      <label for="description" class="col-sm-2 control-label">Job Description</label>
      <div class="col-sm-10">
        <textarea id="description" placeholder="Job description..." class="form-control" name="description" cols="30" rows="10" required="required"></textarea>
      </div>
     </div>

     <div class="form-group">
      <label for="type" class="col-sm-2 control-label">Job Type</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="type" name="type" placeholder="Job Type">
      </div>
     </div>

     <div class="form-group">
      <label for="status" class="col-sm-2 control-label">Job Status</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="status" name="status" placeholder="Job Status">
      </div>
     </div>

     <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-warning">Save</button>
      </div>
     </div>

    </form>
  </div>
</div>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Elixir Jobs!</title>
    <link rel="stylesheet" href="/css/app.css">
    <link rel="stylesheet" href="/css/jobs.css">
    <script src="/js/jquery-2.1.1.min.js"></script>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <span class="logo"></span>
      </div>

      <%= @inner %>

      <div class="footer">
        <p>Made with ♥&nbsp;and<a href="http://phoenixframework.org">Phoenix framewrk</a></p>
      </div>

    </div> <!-- /container -->
  </body>
</html>

web/templates/page/index.html.eex
<div class="row">
  <div class="col-md-4">
    <h2>List Of Jobs</h2>
  </div>
  <div class="col-md-8">
    <a href="<%= job_path(:new) %>"  class="btn btn-danger pull-right">Post a new job</a>
  </div>
</div>

<ul class="list-unstyled" style="">
<%= for job <- @jobs do %>
  <li class="job-list">
    <div class="row">
      <div class="col-md-9">
        <a href="/job/<%= job.id %>">
          <span class="title"><%= job.title %></span>
          <span class="label label-success"><%= job.job_type %></span>
          <span class="label label-default"><%= job.job_status %></span>
        </a>
      </div>
      <div class="col-md-3 buttons" style="text-align: right">
        <a href="<%= job_path(:edit, job.id) %>" class="btn btn-warning btn-sm">Edit</a> &nbsp; &nbsp;
        <a href="/job/<%= job.id %>/delete" class="btn btn-default btn-sm">Delete</a>
      </div>
    </div>
  </li>
<% end %>
</ul>

web/templates/page/job.html.eex
<div class="row">
  <div class="col-md-12">
    <%= if @action == "delete" do %>
      <h2>Are you sure you want to delete <%= @job.title %>?</h2>
    <% else %>
      <h2><%= @job.title %></h2>
    <% end %>
    <h4>
      <span class="label label-success">
        <%= @job.job_type %>
      </span> &nbsp;
      <span class="label label-default">
        <%= @job.job_status %>
      </span>
    </h4>
  </div>
  <div class="col-md-12">
    <p>
      <%= @job.description %>
    </p>
  </div>
  <div class="col-md-12">
    <form action="<%= destroy_path(:destroy) %>" method="post">
      <a href="/" class="btn btn-success">Back</a>
      <%= if @action == "delete" do %>
        <input type="hidden" name="id" value="<%= @job.id %>">
        <button type="submit" class="btn btn-danger pull-right">Delete</button>
      <% end %>
    </form>
  </div>
</div>

web/templates/user/new.html.eex
<h1>New User</h1>
<form class="form-horizontal" action="/users" method="post">
  <div class="form-group">
    <label for="" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-6"><input name="username" class="form-control" placeholder="name@mail.com" type="email" required="required"></div>
  </div>
  <div class="form-group">
    <label for="" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-6"><input name="password" class="form-control" type="password"></div>
  </div>
  <div class="form-group">
    <label for="" class="col-sm-2 control-label">Confirm Password</label>
    <div class="col-sm-6"><input name="confirmPassword" class="form-control" type="password"></div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button class="btn btn-warning" type="submit">Save</button>
    </div>
  </div>
</form>